apiVersion: v2
name: llm-inference-stack
description: A Helm chart to deploy vLLM via KServe behind an Envoy AI Gateway with KEDA autoscaling and Phoenix observability.
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - kserve
  - vllm
  - envoy
  - ai-gateway
  - keda
  - phoenix